name: Trigger webhook to rebuild production site
on:
  schedule:
    - cron: "30 7,15 * * 1-5"

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
